### ISSUE TITLE
Implement rule: an instance of Kind cannot specialize another instance of Kind

### ISSUE THREAD

**Issue by lcbarcellos** [nemo-ufes/ufo-protege-plugin#4]
## Rule
An instance of [`gufo:Kind`](http://purl.org/nemo/gufo#Kind) cannot specialize another instance of [`gufo:Kind`](http://purl.org/nemo/gufo#Kind)

## Source
Third rule from Table 1 of paper [Endurant Types in Ontology-Driven ConceptualModeling: Towards OntoUML 2.0](https://nemo.inf.ufes.br/wp-content/papercite-data/pdf/endurant_types_in_ontology_driven_conceptual_modeling__towards_ontouml_2_0_2018.pdf), presented on page 13 of document.

> From (t11), a class representing a kind cannot specialize another kind.

**Comment by lcbarcellos** [comment]
This constraint, along with the constraint imposed by #3 covers the one expressed in [A modeling infrastructure for OntoUML](https://nemo.inf.ufes.br/wp-content/papercite-data/pdf/a_modeling_infrastructure_for_ontouml_2010.pdf), section 6.1, page 48, with another terminology:

> **Substance Sortal does not specialize Rigid Sortal**
> A Substance Sortal cannot have a Rigid Sortal parent

    context SubstanceSortal inv:
    parents()->select( x | x.oclIsKindOf(RigidSortalClass) )->isEmpty()

A RigidSortalClass in the context of [(CARRARETO, 2010)](https://nemo.inf.ufes.br/wp-content/papercite-data/pdf) is a class which is instance of [`gufo:Kind`](http://purl.org/nemo/gufo#Kind) or is instance of [`gufo:SubKind`](http://purl.org/nemo/gufo#SubKind) in the context of gUFO.

By stating that an instance of [`gufo:Kind`](http://purl.org/nemo/gufo#Kind) cannot specialize another instance of [`gufo:Kind`](http://purl.org/nemo/gufo#Kind), we are already stating that a [`gufo:Kind`](http://purl.org/nemo/gufo#Kind) cannot specialize [`gufo:SubKind`](http://purl.org/nemo/gufo#SubKind) as well, because of, as by #3, a [`gufo:SubKind`](http://purl.org/nemo/gufo#SubKind) must specialize [`gufo:Kind`](http://purl.org/nemo/gufo#Kind).

However, taking into account the transitive inheritance and the constraint from #3, maybe we could rewrite this rule as "An instance of [`gufo:Kind`](http://purl.org/nemo/gufo#Kind) cannot specialize another instance of [`gufo:Sortal`](http://purl.org/nemo/gufo#Sortal)

@jpalmeida, any comments?

**Comment by jpalmeida** [comment]
I agree with your solution. An instance of `ufo:Kind` cannot specialize another instance  of `gufo:Sortal`.
